### ISSUE TITLE
maybe need some words about the environments

### ISSUE THREAD

**Issue by Xuerrui** [noidsirius/SootTutorial#11]
Really thanks for your Tutorial. I am a beginner, I use about 1 day to try to run zhe command such as "java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main". because my computer is windows, I had some stupid try. at last I use ubuntu VM run this command successfully. 
thank u

**Comment by noidsirius** [comment]
Thanks for your comment, I updated the README file to distinguish between Unix and Windows systems.
