### ISSUE TITLE
Gradlew check error

### ISSUE THREAD

**Issue by sapna2504** [noidsirius/SootTutorial#12]
I am getting error like this given below while entering ./gradlew check
Task :buildDemoClass
Compiling directory Android/
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:3: error: package android.content does not exist
import android.content.Context;
                      ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:5: error: package androidx.test.platform.app does not exist
import androidx.test.platform.app.InstrumentationRegistry;
                                 ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:6: error: package androidx.test.ext.junit.runners does not exist
import androidx.test.ext.junit.runners.AndroidJUnit4;
                                      ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:8: error: package org.junit does not exist
import org.junit.Test;
                ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:9: error: package org.junit.runner does not exist
import org.junit.runner.RunWith;
                       ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:11: error: package org.junit does not exist
import static org.junit.Assert.*;
                       ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:18: error: cannot find symbol
@RunWith(AndroidJUnit4.class)
 ^
  symbol: class RunWith
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:3: error: package androidx.appcompat.app does not exist
import androidx.appcompat.app.AlertDialog;
                             ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:4: error: package androidx.appcompat.app does not exist
import androidx.appcompat.app.AppCompatActivity;
                             ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:6: error: package android.content does not exist
import android.content.DialogInterface;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:7: error: package android.content does not exist
import android.content.Intent;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:8: error: package android.os does not exist
import android.os.Bundle;
                 ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:9: error: package android.view does not exist
import android.view.View;
                   ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:11: error: cannot find symbol
public class MainActivity extends AppCompatActivity {
                                  ^
  symbol: class AppCompatActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:15: error: cannot find symbol
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  symbol:   class Bundle
  location: class MainActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:22: error: package View does not exist
    class Button1 implements View.OnClickListener{
                                 ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:24: error: cannot find symbol
        public void onClick(View v) {
                            ^
  symbol:   class View
  location: class MainActivity.Button1
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:30: error: package View does not exist
    class Button2 implements View.OnClickListener{
                                 ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:39: error: cannot find symbol
        public void onClick(View v) {
                            ^
  symbol:   class View
  location: class MainActivity.Button2
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:31: error: package DialogInterface does not exist
        class Dialogue1 implements DialogInterface.OnClickListener{
                                                  ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:34: error: cannot find symbol
            public void onClick(DialogInterface dialog, int which) {
                                ^
  symbol:   class DialogInterface
  location: class MainActivity.Button2.Dialogue1
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:3: error: package android.content does not exist
import android.content.Intent;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:4: error: package android.content does not exist
import android.content.IntentFilter;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:5: error: package android.os does not exist
import android.os.Bundle;
                 ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:6: error: package android.view does not exist
import android.view.View;
                   ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:8: error: package androidx.appcompat.app does not exist
import androidx.appcompat.app.AppCompatActivity;
                             ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:10: error: cannot find symbol
public class SecondActivity extends AppCompatActivity {
                                    ^
  symbol: class AppCompatActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:3: error: package android.content does not exist
import android.content.BroadcastReceiver;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:4: error: package android.content does not exist
import android.content.Context;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:5: error: package android.content does not exist
import android.content.Intent;
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:7: error: cannot find symbol
public class MyReceiver extends BroadcastReceiver {
                                ^
  symbol: class BroadcastReceiver
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:15: error: cannot find symbol
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  symbol:   class Bundle
  location: class SecondActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:15: error: cannot find symbol
    public void onReceive(Context context, Intent intent) {
                          ^
  symbol:   class Context
  location: class MyReceiver
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:15: error: cannot find symbol
    public void onReceive(Context context, Intent intent) {
                                           ^
  symbol:   class Intent
  location: class MyReceiver
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:23: error: package View does not exist
    class Button3 implements View.OnClickListener{
                                 ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:26: error: cannot find symbol
        public void onClick(View v) {
                            ^
  symbol:   class View
  location: class SecondActivity.Button3
./STDemoApp/app/src/test/java/dev/navids/multicomp1/ExampleUnitTest.java:3: error: package org.junit does not exist
import org.junit.Test;
                ^
./STDemoApp/app/src/test/java/dev/navids/multicomp1/ExampleUnitTest.java:5: error: package org.junit does not exist
import static org.junit.Assert.*;
                       ^
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:20: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class ExampleInstrumentedTest
./STDemoApp/app/src/test/java/dev/navids/multicomp1/ExampleUnitTest.java:13: error: cannot find symbol
    @Test
     ^
  symbol:   class Test
  location: class ExampleUnitTest
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:23: error: cannot find symbol
        Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
        ^
  symbol:   class Context
  location: class ExampleInstrumentedTest
./STDemoApp/app/src/androidTest/java/dev/navids/multicomp1/ExampleInstrumentedTest.java:23: error: cannot find symbol
        Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
                             ^
  symbol:   variable InstrumentationRegistry
  location: class ExampleInstrumentedTest
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:14: error: method does not override or implement a method from a supertype
    @Override
    ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:16: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class MainActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:17: error: package R does not exist
        setContentView(R.layout.activity_main);
                        ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:18: error: package R does not exist
        findViewById(R.id.second_act_button).setOnClickListener(new Button1());
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:19: error: package R does not exist
        findViewById(R.id.dialog_button).setOnClickListener( new Button2());
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:23: error: method does not override or implement a method from a supertype
        @Override
        ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:25: error: cannot find symbol
            Intent intent = new Intent(MainActivity.this, SecondActivity.class);
            ^
  symbol:   class Intent
  location: class MainActivity.Button1
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:25: error: cannot find symbol
            Intent intent = new Intent(MainActivity.this, SecondActivity.class);
                                ^
  symbol:   class Intent
  location: class MainActivity.Button1
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:33: error: method does not override or implement a method from a supertype
            @Override
            ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:38: error: method does not override or implement a method from a supertype
        @Override
        ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:45: error: package android.R does not exist
                    .setIcon(android.R.drawable.ic_dialog_alert)
                                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:44: error: package android.R does not exist
                    .setNegativeButton(android.R.string.no, null)
                                                ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:43: error: package android.R does not exist
                    .setPositiveButton(android.R.string.yes, new Dialogue1())
                                                ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:40: error: package AlertDialog does not exist
            new AlertDialog.Builder(MainActivity.this)
                           ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:50: error: method does not override or implement a method from a supertype
    @Override
    ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:52: error: cannot find symbol
        super.onResume();
        ^
  symbol:   variable super
  location: class MainActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:55: error: method does not override or implement a method from a supertype
    @Override
    ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MainActivity.java:57: error: cannot find symbol
        super.onStart();
        ^
  symbol:   variable super
  location: class MainActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:14: error: method does not override or implement a method from a supertype
    @Override
    ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:16: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class SecondActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:18: error: package R does not exist
        setContentView(R.layout.activity_main2);
                        ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:19: error: cannot find symbol
        IntentFilter intentFilter = new IntentFilter(Intent.ACTION_SCREEN_OFF);
        ^
  symbol:   class IntentFilter
  location: class SecondActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:19: error: cannot find symbol
        IntentFilter intentFilter = new IntentFilter(Intent.ACTION_SCREEN_OFF);
                                        ^
  symbol:   class IntentFilter
  location: class SecondActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:19: error: cannot find symbol
        IntentFilter intentFilter = new IntentFilter(Intent.ACTION_SCREEN_OFF);
                                                     ^
  symbol:   variable Intent
  location: class SecondActivity
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:21: error: package R does not exist
        findViewById(R.id.use_button).setOnClickListener(new Button3());
                      ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/SecondActivity.java:25: error: method does not override or implement a method from a supertype
        @Override
        ^
./STDemoApp/app/src/main/java/dev/navids/multicomp1/MyReceiver.java:14: error: method does not override or implement a method from a supertype
    @Override
    ^
./STDemoApp/app/src/test/java/dev/navids/multicomp1/ExampleUnitTest.java:15: error: cannot find symbol
        assertEquals(4, 2 + 2);
        ^
  symbol:   method assertEquals(int,int)
  location: class ExampleUnitTest
70 errors
Compiling directory BasicAPI/
Compiling directory HelloSoot/
Compiling directory IntraAnalysis/

> Task :test

dev.navids.soottutorial.android.CGPTATest > testPointsToAnalysis FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.jimple.infoflow.android.SetupApplication.getClasspath(SetupApplication.java:1085)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1133)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1393)
        at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1265)
        at dev.navids.soottutorial.android.CGPTATest.testPointsToAnalysis(CGPTATest.java:91)

dev.navids.soottutorial.android.CGPTATest > testSPARKCallGraph FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.jimple.infoflow.android.SetupApplication.getClasspath(SetupApplication.java:1085)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1133)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1393)
        at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1265)
        at dev.navids.soottutorial.android.CGPTATest.testSPARKCallGraph(CGPTATest.java:68)

dev.navids.soottutorial.android.CGPTATest > testConfig FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.jimple.infoflow.android.SetupApplication.getClasspath(SetupApplication.java:1085)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1133)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1393)
        at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1265)
        at dev.navids.soottutorial.android.CGPTATest.testConfig(CGPTATest.java:36)

dev.navids.soottutorial.android.CGPTATest > testCHACallGraph FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.jimple.infoflow.android.SetupApplication.getClasspath(SetupApplication.java:1085)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1133)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1393)
        at soot.jimple.infoflow.android.SetupApplication.constructCallgraph(SetupApplication.java:1265)
        at dev.navids.soottutorial.android.CGPTATest.testCHACallGraph(CGPTATest.java:45)

dev.navids.soottutorial.android.AndroidInstrumentTest > testInjectCode FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.Scene.defaultAndroidClassPath(Scene.java:691)
        at soot.Scene.defaultClassPath(Scene.java:620)
        at soot.Scene.getSootClassPath(Scene.java:322)
        at soot.SourceLocator.getClassSource(SourceLocator.java:179)
        at soot.Scene.tryLoadClass(Scene.java:1030)
        at soot.Scene.loadBasicClasses(Scene.java:1744)
        at soot.Scene.loadNecessaryClasses(Scene.java:1845)
        at dev.navids.soottutorial.android.InstrumentUtil.setupSoot(InstrumentUtil.java:34)
        at dev.navids.soottutorial.android.AndroidInstrumentTest.setUp(AndroidInstrumentTest.java:24)

dev.navids.soottutorial.android.AndroidInstrumentTest > testTransformer FAILED
    soot.AndroidPlatformException: Android platform directory '/home/nsl300/Library/Android/sdk/platforms' does not exist!
        at soot.Scene.getAndroidAPIVersion(Scene.java:427)
        at soot.Scene.getAndroidJarPath(Scene.java:392)
        at soot.Scene.defaultAndroidClassPath(Scene.java:691)
        at soot.Scene.defaultClassPath(Scene.java:620)
        at soot.Scene.getSootClassPath(Scene.java:322)
        at soot.SourceLocator.getClassSource(SourceLocator.java:179)
        at soot.Scene.tryLoadClass(Scene.java:1030)
        at soot.Scene.loadBasicClasses(Scene.java:1744)
        at soot.Scene.loadNecessaryClasses(Scene.java:1845)
        at dev.navids.soottutorial.android.InstrumentUtil.setupSoot(InstrumentUtil.java:34)
        at dev.navids.soottutorial.android.AndroidInstrumentTest.setUp(AndroidInstrumentTest.java:24)

11 tests completed, 6 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/nsl300/SootTutorial/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
4 actionable tasks: 2 executed, 2 up-to-date

Is there anyone who can help me with this?

**Comment by noidsirius** [comment]
Closed due to inactivity.
