### ISSUE TITLE
fail to load java.lang.CharSequence 

### ISSUE THREAD

**Issue by CAGeng** [noidsirius/SootTutorial#14]
when I run 
> ./gradlew run --args="HelloSoot"

it occurs:
> Task :run FAILED
Exception in thread "main" java.lang.Error: Error: Failed to load java.lang.CharSequence.

it's said that it's a broken change between jdk7 and 8. But changing to jdk7 didn't work for me.

**Comment by noidsirius** [comment]
Closed due to inactivity.
