### ISSUE TITLE
trying to read .java file and output .java file

### ISSUE THREAD

**Issue by Helen300** [noidsirius/SootTutorial#15]
Hi,

I'm trying to figure out a way to read .java files and output .java files, is there a specific configuration of options that works?
I've tried not specific a src_prec but when I pass in a directory of .java files, I run into an ArrayOutOfBoundsException and in terms of output .java - it seems like there is no option for this? I've tried outputting .dava files but it always results in the following:
<img width="1064" alt="Screen Shot 2021-11-08 at 9 57 52 PM" src="https://user-images.githubusercontent.com/43377525/141008161-625d9e24-7cb6-41f4-8bff-7167c136371d.png">

Thank you!

**Comment by noidsirius** [comment]
Hi,
First, I apologize for getting back so late.  To the best of my knowledge, Soot uses compiled Java files (`.class`) and it does not have a configuration for directly analyzing `.java` files. Also, it outputs in form of compiled Java files (`.class`, `.jar`, `.apk`, etc.). Please reopen this issue if you're aware of any way that Soot can analyze of generate Java files
