### ISSUE TITLE
It used to build but now it's not building anymore

### ISSUE THREAD

**Issue by amadionix** [noidsirius/SootTutorial#6]
Anybody else is experiencing this? It seems like there is a problem with the dependencies. In particular this site cannot be reached anymore: https://soot-build.cs.uni-paderborn.de/

**Comment by noidsirius** [comment]
Thanks for letting me know. It should be fixed now ([PR](https://github.com/noidsirius/SootTutorial/pull/7)).

**Comment by amadionix** [comment]
It works now, thanks!
